### ISSUE TITLE
Vulnerability found in lodash < 4.17.13

### ISSUE THREAD

**Issue by azu** [azu/security-alert#1]
## Vulnerability Information

- Package name:  [lodash](https://www.npmjs.com/package/lodash)
- Package version: 4.17.11
- Package Manifest: https://github.com/azu/security-alert/blob/master/yarn.lock
- Dependencies type: unknown
- Vulnerable version: < 4.17.13
- Patched version: 4.17.13
- GitHub Alert: <https://github.com/azu/security-alert/network/alert/yarn.lock/lodash/open>

## How to fix?

Upgrade lodash to version 4.17.13 or later. For example:

```
"dependencies": {
  "lodash": ">=4.17.13"
}
```

or…

```
"devDependencies": {
  "lodash": ">=4.17.13"
}
```

## Details

- <https://github.com/lodash/lodash/pull/4336>
- <https://nvd.nist.gov/vuln/detail/CVE-2019-10744>

**Comment by Gby56** [comment]
# lol

## Results

- **[ERROR]** **[js/xss]**  `Cross-site scripting vulnerability due to \[user-provided value\]\(1\).`
    - https://github.com/azu/security-alert/blob/master/examples/Xss.js#L4
    - https://github.com/azu/security-alert/blob/master/examples/Xss2.js#L4



## Suppressed Results

Nothing here.



## Rules information

<details><summary>Rules details</summary>


    - js/xss [error] 

    > Client-side cross-site scripting


## Tool information
- Name: CodeQL command-line toolchain
- Organization: GitHub
- Version: 2.2.4
